# Welcome to Mago!
# For full documentation, see https://mago.carthage.software/tools/overview
php-version = "8.2.0"

[source]
workspace = "."
paths = ["Modules/", "packages/", "app/", "database/factories/", "database/seeders/"]
includes = ["vendor"]
excludes = []

[formatter]
print-width = 120
tab-width = 4
use-tabs = false
space-before-arrow-function-parameter-list-parenthesis = true

[linter]
integrations = ["symfony", "laravel"]

[linter.rules]
ambiguous-function-call = { enabled = false }
literal-named-argument = { enabled = false }
halstead = { enabled = false }
prefer-static-closure = { enabled = false }
prefer-early-continue = { enabled = false }
no-else-clause = { enabled = false }
function-name = { enabled = false }
too-many-methods = { enabled = false }
kan-defect = { enabled = false }
cyclomatic-complexity = { enabled = false }
no-assign-in-condition = { enabled = false }
no-shorthand-ternary = { enabled = false }
no-empty-catch-clause = { enabled = false }
excessive-nesting = { enabled = false }

[analyzer]
find-unused-definitions = true
find-unused-expressions = false
analyze-dead-code = false
memoize-properties = true
allow-possibly-undefined-array-keys = true
check-throws = false
check-missing-override = false
find-unused-parameters = false
strict-list-index-checks = false
no-boolean-literal-comparison = false
check-missing-type-hints = false
register-super-globals = true
